/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nihao' at '17-9-14 上午12:35' with Gradle 2.11
 *
 * @author nihao, @date 17-9-14 上午12:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
